worker_processes auto;
error_log /var/log/nginx/error.log warn;
pid /var/run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    sendfile on;
    keepalive_timeout 65;
    client_max_body_size 20M;
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml;

    upstream backend_api {
        server adsentinel-api:4000;
        keepalive 8;
    }

    upstream frontend_app {
        server adsentinel-ui:80;
        keepalive 8;
    }

    limit_req_zone $binary_remote_addr zone=api:10m  rate=60r/m;
    limit_req_zone $binary_remote_addr zone=auth:10m rate=10r/m;

    server {
        listen 80;
        server_name _;

        location /api/auth/ {
            limit_req          zone=auth burst=5 nodelay;
            proxy_pass         http://backend_api;
            proxy_http_version 1.1;
            proxy_set_header   Connection "";
            proxy_set_header   Host              $host;
            proxy_set_header   X-Real-IP         $remote_addr;
            proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Proto $scheme;
            proxy_connect_timeout 5s;
            proxy_read_timeout    30s;
        }

        location /api/ {
            limit_req          zone=api burst=20 nodelay;
            proxy_pass         http://backend_api;
            proxy_http_version 1.1;
            proxy_set_header   Connection "";
            proxy_set_header   Host              $host;
            proxy_set_header   X-Real-IP         $remote_addr;
            proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Proto $scheme;
            proxy_connect_timeout 5s;
            proxy_read_timeout    60s;
        }

        location /reports/ {
            alias /var/www/reports/;
            add_header Content-Disposition attachment;
        }

        location /uploads/logos/ {
            alias /usr/share/nginx/html/uploads/logos/;
            expires 7d;
        }

        location / {
            proxy_pass         http://frontend_app;
            proxy_http_version 1.1;
            proxy_set_header   Connection "";
            proxy_set_header   Host $host;
            proxy_connect_timeout 5s;
        }
    }
}
